db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/students
  user: dev
  password: dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    driver-class-name: org.postgresql.Driver
    username: dev
    password: dev
